### ISSUE TITLE
Fix sign extension of immediates for LBU/LHU instructions

### ISSUE THREAD

**Issue by HarryR** [AnthonyMichaelTDM/RISC-V_emulator#1]
Ran into this bug with newlib's `strlen` implementation, using `gcc` from https://github.com/stnolting/riscv-gcc-prebuilt

Bit of a hairpulling debugging session to track this one down, anyway, the root cause is:

https://github.com/AnthonyMichaelTDM/RISC-V_emulator/blob/817b2f5e3703da68f281df570e4bda0f15c90675/src/emulator/decode.rs#L90-L92

Which incorrectly masks off 16 bits instead of 12 bits.

and

https://github.com/AnthonyMichaelTDM/RISC-V_emulator/blob/817b2f5e3703da68f281df570e4bda0f15c90675/src/emulator/decode.rs#L137-L143

The instruction decoder was not sign-extending immediates for LBU and LHU 
instructions, causing them to treat address offsets as large positive values 
instead of small negative ones. This caused out-of-bounds memory access when 
these instructions were used with negative offsets.

---

To fix this you need to make 2 changes:

e.g. 
```rust
                let mut imm: i32 =
                    // extract the lowest 12 bits of the immediate from the machine code
                    (machine_code >> 20) & 0xFFF;

...

                // if the instruction is not one of the unsigned instructions, sign extend the immediate
                if !matches!(
                    operation,
                    /*ITypeOperation::Lbu | ITypeOperation::Lhu |*/ ITypeOperation::Sltiu
                ) {
                    imm = imm << 20 >> 20;
                }
```

----

Aside from that, really useful code, and I'm slowly verifying all the instructions work correctly.

I noticed you haven't explicitly licensed this code, are you happy for me to use it under the terms of the MIT or Apache-2.0 licenses (with copyright attribution of course).

**Comment by AnthonyMichaelTDM** [comment]
Great catch, thank you!

I'll push a commit including a license, but yes, MIT/Apache-2.0 with attribution is acceptable

**Comment by AnthonyMichaelTDM** [comment]
This issue is fixed by the most recent commits, specifically  72c77767da39a136bf6962504b3f39577638b863, I probably should've done a PR, but I was feeling lazy

**Comment by AnthonyMichaelTDM** [comment]
feel free to reopen if necessary

**Comment by HarryR** [comment]
Awesome :+1:  Have a happy new year.

Will ping you when the thing I'm hacking on is in a better state, or if I find more problems.

**Comment by AnthonyMichaelTDM** [comment]
Sounds great! I'm very curious about what you're using this repo for and would love to hear more. Happy new year to you as well.

**Comment by AnthonyMichaelTDM** [comment]
@HarryR any updates?
